### PR TITLE
fix: provide `SWIFTPM_MODULE_BUNDLE` macro for Objective-C targets with resources

### LINKED ISSUE #372: Use of undeclared identifier 'SWIFTPM_MODULE_BUNDLE'
When using ObjC dependency you will get "Use of undeclared identifier 'SWIFTPM_MODULE_BUNDLE'" if there are Bundle Resources.

Package example https://github.com/AppLovin/AppLovin-MAX-Swift-Package

### LINKED ISSUE #774: SWIFTPM_MODULE_BUNDLE is not defined by rules_swift_package_manager for ObjC targets
Apparently SWIFTPM_MODULE_BUNDLE is thing, it is C precompiller flag defined for SMP packages

Usage example
https://github.com/pocketsvg/PocketSVG/blob/10c6885e427e88d35fbb64010fbd6385cb58fef7/Sources/SVGEngine.mm#L899

There is similar bugreport for Tuist:
https://github.com/tuist/tuist/issues/3785

### PR DESCRIPTION
**Pull request by cgrindel**
- Generate `SWIFTPM_MODULE_BUNDLE` macro [inspired by the one provided by SPM](https://github.com/apple/swift-package-manager/blob/8387798811c6cc43761c5e1b48df2d3412dc5de4/Sources/Build/BuildDescription/ClangTargetBuildDescription.swift#L390).
- Ensure that the macro is available to all of the ObjC code by adding the `-include` flag to the `copts` with the location of the resource accessor header file.
- Update the `resources_example` to use a vendored version of [AppLovin-MAX-Swift-Package](https://github.com/AppLovin/AppLovin-MAX-Swift-Package). This package has an ObjC target with resources that expects the `SWIFTPM_MODULE_BUNDLE` macro to be present.

Closes #372.
Closes #774.

### CODE REVIEW

**Comment by cgrindel** [comment]
cc: @denis15yo, @krypt-lx

**Comment by krypt-lx** [comment]
How can I test this version? The project uses bzlmod

**Comment by krypt-lx** [comment]
Like I said, we are using blzmod and configuration inside MODULE.bazel file. it doesn't seems like I can use `http_archive` in  MODULE file or move part of initialisation into WORKSPACE

**Comment by cgrindel** [comment]
Sorry. I misread your post. Add [git_override](https://bazel.build/rules/lib/globals/module#git_override) to your `MODULE.bazel` after the `bazel_dep`. In other words, keep the `bazel_dep` and add a `git_override`. Use the GitHub UI to determine the current commit for the branch.

**Comment by cgrindel** [comment]
@krypt-lx Also, could you report back when you have had a chance to test it?

**Comment by krypt-lx** [comment]
Sorry, I *just* tested it
This commit actually breaks project compilation. One moment, will create an issue

**Comment by krypt-lx** [comment]
Ok, it is reported already:
https://github.com/cgrindel/rules_swift_package_manager/issues/798

except for me it is swiftpkg_pocketsvg/swiftpkg_sdwebimage

**Comment by cgrindel** [comment]
@krypt-lx #803 fixes the duplicate symbol issue. The CI is failing for another reason related to Go versions. I will try to get that straightened out and the fix merged, shortly.

**Comment by krypt-lx** [comment]
Just tested 803 - seems to work

**Pull request merged**
