### PR TITLE
feat: add support for `.enableExperimentalFeature()`

### PR DESCRIPTION
**Pull request by jpsim**
This fixes the `swift-atomics` package.

### CODE REVIEW

**Comment by cgrindel** [comment]
Is there something that we can add to the examples that will exercise this?

**Comment by cgrindel** [comment]
Is this PR to support [this flag](https://github.com/apple/swift-atomics/blob/cd142fd2f64be2100422d658e7411e39489da985/Package.swift#L25)?

**Comment by cgrindel** [comment]
Instead of adding it to an example, perhaps we can add a test in `swiftpkg_build_files_tests.bzl`.

**Comment by jpsim** [comment]
> Is this PR to support [this flag](https://github.com/apple/swift-atomics/blob/cd142fd2f64be2100422d658e7411e39489da985/Package.swift#L25)?

Yes

> Instead of adding it to an example, perhaps we can add a test in swiftpkg_build_files_tests.bzl.

I'll take a look.

**Review by cgrindel — APPROVED** [review]

**Pull request merged**
