### PR TITLE
fix: Use `swift_interop_hint` instead of `swift_module` tag

### PR DESCRIPTION
**Pull request by brentleyjones**
Needed for rules_swift 2.0+. Only works with rules_swift 2.0+.

### CODE REVIEW

**Comment by brentleyjones** [comment]
I can't think of a good way to determine if we are depending on rules_swift 2.0 or not, so right now this is unconditional. Ideally we would only make this change if transitively depending on rules_swift 2.0.

**Review by luispadron — APPROVED** [review]

**Review by cgrindel — APPROVED** [review]

**Comment by brentleyjones** [comment]
Needs https://github.com/cgrindel/rules_swift_package_manager/pull/1156.

**Review by cgrindel — APPROVED** [review]
Thanks!

**Comment by cgrindel** [comment]
I see this in the firbase example failure:
```log
ERROR: rules_apple@3.6.0 depends on rules_swift@1.18.0 with compatibility level 1, but <root> depends on rules_swift@2.1.0 with compatibility level 2 which is different
```

Is there a corresponding rules_apple upgrade that needs to be applied?

**Comment by brentleyjones** [comment]
It's a bad error message (https://github.com/bazelbuild/bazel/issues/22972), it was actually **rules_xcodeproj** that needed to be updated.

**Review by luispadron — APPROVED** [review]

**Pull request merged**
