### PR TITLE
feat: Use GRPC from swift package manager

### PR DESCRIPTION
**Pull request by AttilaTheFun**
This PR updates the GRPC examples to use the GRPC obtained through RSPM instead of the one in rules_swift.
I was unable to land this previously because tests were failing on ubuntu without the alwayslink = True flag.
RSPM now sets this flag so it should work as expected.

### CODE REVIEW

**Comment by AttilaTheFun** [comment]
@cgrindel I think this is ready to go, and the Stripe test failure is unrelated to this PR.

**Comment by cgrindel** [comment]
I already moved these examples to [swift_gazelle_plugin](https://github.com/cgrindel/swift_gazelle_plugin). Can we apply this PR over there?

**Comment by AttilaTheFun** [comment]
Oh ok — I wasn’t sure if it was ready to use. When will it be published on the Bazel registry?

**Comment by cgrindel** [comment]
I am working on it, right now. 🙂

**Comment by AttilaTheFun** [comment]
@cgrindel Ok I ported the PR over to the new repo here: https://github.com/cgrindel/swift_gazelle_plugin/pull/7

**Pull request closed without merging**
