### PR TITLE
feat: Add support RegexBuilder built-in framework

### PR DESCRIPTION
**Pull request by luispadron**
Adds support for built-in frameworks like [RegexBuilder](https://developer.apple.com/documentation/regexbuilder).

### CODE REVIEW

**Comment by luispadron** [comment]
Fixes the issue seen in #728

**Comment by luispadron** [comment]
hmm running `bazel run //tools/generate_builtin_frameworks` removes `RegexBuilder` but updates the file with more frameworks

**Comment by luispadron** [comment]
Added support to the generator for picking up `.swiftmodule`s without `.framework` like the `RegexBuilder` framework

**Review by cgrindel — APPROVED** [review]

**Comment by luispadron** [comment]
This is probably having unintended issues elsewhere since it's picking up some other stuff in `/usr/lib/swift`:

```
ld: framework not found os
```

Thoughts @cgrindel

**Comment by luispadron** [comment]
I can also remove the swift module lookup changes and just add RegexBuilder to the other frameworks list, similar to XCTest. I'm not sure why this isn't a framework in System/Frameworks

**Comment by cgrindel** [comment]
> I can also remove the swift module lookup changes and just add RegexBuilder to the other frameworks list, similar to XCTest. I'm not sure why this isn't a framework in System/Frameworks

That sounds reasonable to me.

**Comment by luispadron** [comment]
Updated

**Review by cgrindel — APPROVED** [review]

**Pull request merged**
