### PR TITLE
chore(deps): update dependency stripe-ios to v23.27.0

### PR DESCRIPTION
**Pull request by jpsim**
Required syncing the `PaymentSheet` files with the latest upstream version. That's the bulk of the line of code changes in this PR.

Demonstrates the "dependency checking of directories is unsound" warning:

```console
$ cd examples/stripe_example
$ bazel build //... --action_env=BAZEL_FORCE_REBUILD="$(date)"
WARNING: PaymentSheetExample/BUILD.bazel:36:16: input 'Stripe3DS2/Stripe3DS2/Resources/Stripe3DS2.xcassets' to //PaymentSheet/PaymentSheetExample:iosapp is a directory; dependency checking of directories is unsound
WARNING: PaymentSheetExample/BUILD.bazel:36:16: input 'StripeUICore/StripeUICore/Resources/StripeUICore.xcassets' to //PaymentSheet/PaymentSheetExample:iosapp is a directory; dependency checking of directories is unsound
WARNING: PaymentSheetExample/BUILD.bazel:36:16: input 'StripePaymentsUI/StripePaymentsUI/Resources/StripePaymentsUI.xcassets' to //PaymentSheet/PaymentSheetExample:iosapp is a directory; dependency checking of directories is unsound
WARNING: PaymentSheetExample/BUILD.bazel:36:16: input 'StripePaymentSheet/StripePaymentSheet/Resources/StripePaymentSheet.xcassets' to //PaymentSheet/PaymentSheetExample:iosapp is a directory; dependency checking of directories is unsound
```

### CODE REVIEW

**Review by cgrindel — APPROVED** [review]
Thank you!

**Comment by jpsim** [comment]
Seems to still get stuck at the `Testing //examples:stripe_example_test_bazel_.bazelversion` step with Xcode 15 on CI as tracked in https://github.com/cgrindel/rules_swift_package_manager/issues/762.

**Comment by jpsim** [comment]
> Seems to still get stuck

Not stuck, just takes an extremely long time. `PASSED in 980.9s`

@cgrindel I'll leave it up to you if this is too long for a CI job.

**Comment by cgrindel** [comment]
Well, we could pare back the UI test. If I recall, we just took what was in the stripe example. For now, I think that we can just merge it. If you have any suggestions, please let me know.

**Comment by jpsim** [comment]
> Well, we could pare back the UI test

I actually did that here so it only runs a single test. Runs in a few seconds locally.

**Comment by cgrindel** [comment]
That is good to know. Thanks!

**Pull request merged**
