### PR TITLE
fix: copy Gazelle config to scope directives properly

### PR DESCRIPTION
**Pull request by adzenith**
A directive like `# gazelle:swift_generate_proto_libraries false` is intended to apply to the current package and all subpackages. Currently, though, it's being applied to all further packages that Gazelle parses. This is because we have a shared reference to a single SwiftConfig object that is being updated in place, so changes accidentally propagate further than they should.

This PR instead makes a clone of the SwiftConfig for the current package, based on the way it's done [in Gazelle itself](https://github.com/bazelbuild/bazel-gazelle/blob/master/language/proto/config.go#L208-L210).

### CODE REVIEW

**Review by cgrindel — APPROVED** [review]
Thanks for the contribution!

**Comment by adzenith** [comment]
@cgrindel I added a test in an examples dir. I verified locally that it fails on `main` and that it passes with this change.

`main`:
```
❯ buildozer delete //protos/echoservice:echoservice_swift_proto
fixed /home/niko/rules_swift_package_manager/examples/grpc_example/protos/echoservice/BUILD.bazel

❯ bazel run //:update_build_files && git diff HEAD --quiet
WARNING: Option 'experimental_remote_build_event_upload' is deprecated: Use --remote_build_event_upload instead
INFO: Invocation ID: 29137f14-403d-484f-9326-6d2e7facf215
WARNING: Option 'experimental_remote_build_event_upload' is deprecated: Use --remote_build_event_upload instead
INFO: Analyzed target //:update_build_files (1 packages loaded, 3 targets configured).
INFO: Found 1 target...
Target //:update_build_files up-to-date:
  bazel-bin/update_build_files-runner.bash
  bazel-bin/update_build_files
INFO: Elapsed time: 0.204s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/update_build_files
gazelle: Unable to find dependency labels for GRPC, NIOCore, NIOPosix, SwiftProtobuf, protos_echoservice_echoservice_proto, protos_echoservice_messages_messages_proto
gazelle: Unable to find dependency labels for GRPC, NIOCore, NIOPosix, protos_echoservice_echoservice_proto, protos_echoservice_messages_messages_proto
gazelle: Unable to find dependency labels for GRPC, NIOCore, NIOPosix, protos_echoservice_echoservice_proto, protos_echoservice_messages_messages_proto

❯ echo $?
1

❯ git diff
diff --git examples/grpc_example/protos/echoservice/BUILD.bazel examples/grpc_example/protos/echoservice/BUILD.bazel
index 70e6e18..c5229ca 100644
--- examples/grpc_example/protos/echoservice/BUILD.bazel
+++ examples/grpc_example/protos/echoservice/BUILD.bazel
@@ -1,4 +1,4 @@
-load("@build_bazel_rules_swift//swift:swift.bzl", "swift_grpc_library", "swift_proto_library")
+load("@build_bazel_rules_swift//swift:swift.bzl", "swift_grpc_library")
 load("@rules_proto//proto:defs.bzl", "proto_library")
 
 proto_library(
@@ -8,12 +8,6 @@ proto_library(
     deps = ["//protos/echoservice/messages:messages_proto"],
 )
 
-swift_proto_library(
-    name = "echoservice_swift_proto",
-    visibility = ["//visibility:public"],
-    deps = [":echoservice_proto"],
-)
-
 swift_grpc_library(
     name = "echoservice_client_swift_grpc",
     srcs = [":echoservice_proto"],
...
```

This PR:
```
❯ buildozer delete //protos/echoservice:echoservice_swift_proto
fixed /home/niko/rules_swift_package_manager/examples/grpc_example/protos/echoservice/BUILD.bazel

❯ bazel run //:update_build_files && git diff HEAD --quiet
WARNING: Option 'experimental_remote_build_event_upload' is deprecated: Use --remote_build_event_upload instead
INFO: Invocation ID: fb1614ec-f6f6-4af9-a157-cd6a8bf3c55f
WARNING: Option 'experimental_remote_build_event_upload' is deprecated: Use --remote_build_event_upload instead
INFO: Analyzed target //:update_build_files (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:update_build_files up-to-date:
  bazel-bin/update_build_files-runner.bash
  bazel-bin/update_build_files
INFO: Elapsed time: 0.190s, Critical Path: 0.05s
INFO: 3 processes: 2 disk cache hit, 1 internal.
INFO: Build completed successfully, 3 total actions
INFO: Running command line: bazel-bin/update_build_files
gazelle: Unable to find dependency labels for GRPC, NIOCore, NIOPosix, SwiftProtobuf
gazelle: Unable to find dependency labels for GRPC, NIOCore, NIOPosix
gazelle: Unable to find dependency labels for GRPC, NIOCore, NIOPosix

❯ git diff
diff --git examples/grpc_example/protos/echoservice/BUILD.bazel examples/grpc_example/protos/echoservice/BUILD.bazel
index 70e6e18..713d482 100644
--- examples/grpc_example/protos/echoservice/BUILD.bazel
+++ examples/grpc_example/protos/echoservice/BUILD.bazel
@@ -8,12 +8,6 @@ proto_library(
     deps = ["//protos/echoservice/messages:messages_proto"],
 )
 
-swift_proto_library(
-    name = "echoservice_swift_proto",
-    visibility = ["//visibility:public"],
-    deps = [":echoservice_proto"],
-)
-
 swift_grpc_library(
     name = "echoservice_client_swift_grpc",
     srcs = [":echoservice_proto"],
@@ -37,3 +31,9 @@ swift_grpc_library(
     visibility = ["//visibility:public"],
     deps = [":echoservice_swift_proto"],
 )
+
+swift_proto_library(
+    name = "echoservice_swift_proto",
+    visibility = ["//visibility:public"],
+    deps = [":echoservice_proto"],
+)
```

**Comment by AttilaTheFun** [comment]
@cgrindel That seems reasonable to me!

@adzenith FYI if you're using the swift proto library generation I added to this repo, I recently merged a big PR to write a new swift_proto_library rule in rules_swift and deprecate the old swift_proto_library and swift_grpc_library rules (they're still present in the repo, just marked as deprecated).
https://github.com/bazelbuild/rules_swift/pull/1140

The new swift_proto_library rule functions much closer to go_proto_library and allows for customizable module names and  proto compilers (including SwiftProtobuf and grpc-swift from Swift Package Manager through this repo).

I have a PR into this repo to add support for the new rules:
https://github.com/cgrindel/rules_swift_package_manager/pull/834
It already covers all of the cases covered by the current gazelle plugin and then some.

I'm trying to get it working at Snapchat for our entire pb_schema repository with 6000+ protos and many obscure edge cases (multiple proto packages in the same directory, proto packages spanning multiple directories, multiple proto import prefixes etc.).

Once I have it working for our entire pb_schema repo, I'll re-open it here.
Feel free to test it out in a branch and let me know if you have any issues with the new rules or generated targets.

**Comment by adzenith** [comment]
The new rule looks great. I'll see if I have time to try out the branch; otherwise we'll use it when it lands :)

As a bonus, it looks like this PR [doesn't conflict](https://github.com/cgrindel/rules_swift_package_manager/pull/834/files#diff-faa77540fff08eeba3b7f725782c86e776aade160c18cb4cc65661b30c917818L152) with yours!

**Comment by AttilaTheFun** [comment]
Awesome, yeah I don't mind rebasing it. I'll clean it up before I take it out of draft mode.

By the way, @cgrindel, is there any way we can avoid the MODULE.lock files for examples? They add thousands of lines to the diff which might scare off reviewers 😅

**Comment by cgrindel** [comment]
@adzenith Can you run `bazel run //:tidy` and push the changes? The tidy failure is probably due to the new Bazel packages needing to be added to the deleted list for the root workspace.

**Comment by adzenith** [comment]
@cgrindel done!

**Comment by adzenith** [comment]
The test was using `git diff`, which was a bad idea and also didn't work. It now runs Gazelle in `--mode=diff`, which sets the exit code if the BUILD files aren't up to date. Should pass CI now.

**Comment by adzenith** [comment]
Thank you!

**Pull request merged**
